import { ThemedText } from "@src/components/shared_components/ThemedText";
import { generateDescriptionSuggestion } from "@src/utils/productFormatter";
import React, { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { StyleSheet, View } from "react-native";

interface ProductDescriptionProps {
  description?: string;
  activeFont: string;
  subCategory?: string;
  details?: Record<string, any>;
}

const ProductDescription: React.FC<ProductDescriptionProps> = ({
  description,
  subCategory,
  details,
}) => {
  const { t, i18n } = useTranslation();
  const [displayDescription, setDisplayDescription] = useState(description);

  // Check if description looks like it was generated by our suggestion tool
  const isGeneratedDescription = (desc: string | undefined): boolean => {
    if (!desc) return false;
    // Check for Khmer or English summary patterns
    return (
      desc.includes("ព័ត៌មានសង្ខេប:") ||
      desc.includes("Summary:") ||
      desc.includes("ម៉ាក:") ||
      desc.includes("Brand:")
    );
  };

  // Regenerate description when language changes or when props change
  useEffect(() => {
    if (
      isGeneratedDescription(description) &&
      subCategory &&
      details &&
      Object.keys(details).length > 0
    ) {
      // Regenerate description in current language
      const suggestion = generateDescriptionSuggestion(
        subCategory,
        "", // empty current description to force regeneration
        details,
        i18n.language,
      );
      setDisplayDescription(suggestion.suggested);
    } else {
      // Use original description if not generated or missing details
      setDisplayDescription(description);
    }
  }, [description, subCategory, details, i18n.language]);

  if (!displayDescription) {
    return null;
  }

  return (
    <View style={styles.section}>
      <ThemedText style={styles.sectionTitle}>
        {t("productDetail.description")}
      </ThemedText>
      <ThemedText style={styles.descriptionText}>
        {displayDescription}
      </ThemedText>
    </View>
  );
};

const styles = StyleSheet.create({
  section: {
    marginBottom: 20,
    paddingHorizontal: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 12,
  },
  descriptionText: {
    fontSize: 15,
    lineHeight: 22,
    opacity: 0.8,
  },
});

export default ProductDescription;
