/**
 * Popular brands for each product subcategory
 */
export const POPULAR_BRANDS: Record<string, string[]> = {
  // Electronics & Gadgets
  Phone: [
    "Apple",
    "Samsung",
    "Xiaomi",
    "Oppo",
    "Vivo",
    "Realme",
    "OnePlus",
    "Google",
    "Huawei",
    "Motorola",
    "Nokia",
    "Others",
  ],
  Tablet: [
    "Apple",
    "Samsung",
    "iPad",
    "Xiaomi",
    "Lenovo",
    "Huawei",
    "Sony",
    "Others",
  ],
  "Smart Watch": [
    "Apple",
    "Samsung",
    "Garmin",
    "Fitbit",
    "Fossil",
    "Xiaomi",
    "Huawei",
    "Others",
  ],
  "Phone Accessories": [
    "Apple",
    "Samsung",
    "Anker",
    "Belkin",
    "OtterBox",
    "Spigen",
    "Others",
  ],

  // Vehicles
  Car: [
    "Toyota",
    "Honda",
    "Hyundai",
    "Kia",
    "Ford",
    "BMW",
    "Mercedes-Benz",
    "Nissan",
    "Mazda",
    "Volkswagen",
    "Suzuki",
    "Mitsubishi",
    "Chevrolet",
    "Others",
  ],
  Bicycle: [
    "Trek",
    "Giant",
    "Specialized",
    "Cannondale",
    "Scott",
    "Merida",
    "Others",
  ],
  Motorcycle: [
    "Honda",
    "Yamaha",
    "Suzuki",
    "Kawasaki",
    "Harley-Davidson",
    "KTM",
    "BMW",
    "Ducati",
    "Royal Enfield",
    "Others",
  ],
  Lorries: [
    "Volvo",
    "Scania",
    "MAN",
    "Daf",
    "Iveco",
    "Hino",
    "Others",
  ],
  Tractors: [
    "John Deere",
    "Case IH",
    "CLAAS",
    "Kubota",
    "Massey Ferguson",
    "Fendt",
    "Others",
  ],
  "Tuk Tuk & Remork": [
    "Bajaj",
    "Tuktuk",
    "Rickshaw",
    "Others",
  ],
  "Parts & Accessories": [
    "Bosch",
    "Denso",
    "Continental",
    "Brembo",
    "Others",
  ],
  "Vehicles For Rent": [
    "Toyota",
    "Honda",
    "Nissan",
    "Hyundai",
    "Others",
  ],

  // Health & Beauty
  "Skin Care": [
    "Estée Lauder",
    "L'Oréal",
    "Shiseido",
    "Clinique",
    "MAC",
    "Revlon",
    "Maybelline",
    "Dove",
    "Cetaphil",
    "CeraVe",
    "Neutrogena",
    "Others",
  ],
  "Hair Care": [
    "L'Oréal",
    "Pantene",
    "Dove",
    "Head & Shoulders",
    "TRESemmé",
    "Garnier",
    "Schwarzkopf",
    "Others",
  ],
  Makeup: [
    "MAC",
    "Urban Decay",
    "Too Faced",
    "Fenty Beauty",
    "Charlotte Tilbury",
    "Huda Beauty",
    "Anastasia Beverly Hills",
    "Others",
  ],
  "Natural & Organic": [
    "Origins",
    "Burt's Bees",
    "Avalon Organics",
    "Weleda",
    "Juice Beauty",
    "Others",
  ],

  // Furniture (no specific brands)
  "Tables & Desks": ["Generic", "Various Brands", "Others"],
  "Chairs & Sofas": ["Generic", "Various Brands", "Others"],
  "Wardrobes & Cabinets": ["Generic", "Various Brands", "Others"],
  "Shelves & Drawers": ["Generic", "Various Brands", "Others"],
  "Beds & Mattresses": ["Generic", "Various Brands", "Others"],
  "Curtain & Carpet": ["Generic", "Various Brands", "Others"],
  Kitchenware: [
    "Le Creuset",
    "Zwilling",
    "Fissler",
    "Tramontina",
    "T-fal",
    "Others",
  ],
  "Household Items": [
    "Generic",
    "Various Brands",
    "Others",
  ],
  "Handicrafts-Paintings": ["Generic", "Various Brands", "Others"],

  // Fashion
  "Women's Fashion": [
    "Zara",
    "H&M",
    "Forever 21",
    "ASOS",
    "Uniqlo",
    "Gap",
    "Others",
  ],
  "Men's Fashion": [
    "Zara",
    "H&M",
    "Uniqlo",
    "Gap",
    "Banana Republic",
    "Others",
  ],
  "Baby & Kids": [
    "OshKosh B'gosh",
    "Carter's",
    "Gap Kids",
    "Zara Kids",
    "H&M Kids",
    "Others",
  ],
  "Fashion Accessories": [
    "Coach",
    "Michael Kors",
    "Guess",
    "Tommy Hilfiger",
    "Others",
  ],

  // Computers
  Laptop: [
    "Apple",
    "Dell",
    "HP",
    "Lenovo",
    "Asus",
    "Acer",
    "MSI",
    "Sony",
    "Samsung",
    "Others",
  ],
  Desktop: [
    "Dell",
    "HP",
    "Lenovo",
    "Asus",
    "Acer",
    "Apple",
    "Corsair",
    "Others",
  ],
  "All in One": [
    "Apple",
    "Dell",
    "HP",
    "Asus",
    "Lenovo",
    "Others",
  ],
  "Monitor Printer & Scanner": [
    "Dell",
    "HP",
    "Canon",
    "Epson",
    "Brother",
    "Samsung",
    "Others",
  ],

  // Real Estate
  House: ["N/A"],
  Condo: ["N/A"],
  Apartment: ["N/A"],
  Land: ["N/A"],
  Commercial: ["N/A"],

  // Electronics & Appliances
  "Washing Machines": [
    "LG",
    "Samsung",
    "Whirlpool",
    "Electrolux",
    "Bosch",
    "Haier",
    "IFB",
    "Others",
  ],
  Fridges: [
    "LG",
    "Samsung",
    "Whirlpool",
    "Electrolux",
    "Bosch",
    "Haier",
    "Others",
  ],
  "Air Conditioning": [
    "Daikin",
    "LG",
    "Samsung",
    "Panasonic",
    "Midea",
    "Others",
  ],
  Tools: [
    "DeWalt",
    "Makita",
    "Bosch",
    "Milwaukee",
    "Hitachi",
    "Others",
  ],
  Machinery: [
    "Various Brands",
    "Others",
  ],
  "Security Camera": [
    "Hikvision",
    "Dahua",
    "Uniview",
    "Axis",
    "Sony",
    "Others",
  ],
  "TVs & Audio": [
    "Samsung",
    "LG",
    "Sony",
    "Panasonic",
    "Philips",
    "TCL",
    "Others",
  ],
  "Video games": [
    "Nintendo",
    "PlayStation",
    "Xbox",
    "Sega",
    "Others",
  ],
  Toys: [
    "LEGO",
    "Mattel",
    "Hasbro",
    "Playmobil",
    "Melissa & Doug",
    "Others",
  ],
};

/**
 * Popular RAM options for devices
 */
export const POPULAR_RAM: Record<string, string[]> = {
  Phone: ["4GB", "6GB", "8GB", "12GB", "16GB", "Others"],
  Tablet: ["4GB", "6GB", "8GB", "12GB", "Others"],
  "Smart Watch": ["512MB", "1GB", "2GB", "Others"],
  Laptop: ["8GB", "16GB", "32GB", "64GB", "Others"],
  Desktop: ["8GB", "16GB", "32GB", "64GB", "128GB", "Others"],
  "All in One": ["8GB", "16GB", "32GB", "64GB", "Others"],
};

/**
 * Popular storage options for devices
 */
export const POPULAR_STORAGE: Record<string, string[]> = {
  Phone: ["64GB", "128GB", "256GB", "512GB", "1TB", "Others"],
  Tablet: ["64GB", "128GB", "256GB", "512GB", "Others"],
  "Smart Watch": ["4GB", "8GB", "16GB", "32GB", "Others"],
  Laptop: ["256GB", "512GB", "1TB", "2TB", "Others"],
  Desktop: ["256GB", "512GB", "1TB", "2TB", "4TB", "Others"],
  "All in One": ["256GB", "512GB", "1TB", "2TB", "Others"],
};

/**
 * Popular material options
 */
export const POPULAR_MATERIALS: Record<string, string[]> = {
  "Tables & Desks": ["Wood", "MDF", "Metal", "Glass", "Plastic", "Others"],
  "Chairs & Sofas": ["Fabric", "Leather", "Wood", "Metal", "Plastic", "Others"],
  "Wardrobes & Cabinets": ["Wood", "MDF", "Metal", "Plastic", "Others"],
  "Shelves & Drawers": ["Wood", "MDF", "Metal", "Plastic", "Others"],
  "Beds & Mattresses": ["Wood", "Metal", "Fabric", "Foam", "Spring", "Latex", "Others"],
  "Curtain & Carpet": ["Cotton", "Polyester", "Velvet", "Wool", "Nylon", "Others"],
  Kitchenware: ["Stainless Steel", "Aluminum", "Cast Iron", "Ceramic", "Glass", "Plastic", "Others"],
};
